defaults:
  - view_sampler: bounded

name: dfc2019
roots: [/project/winston/datasets/DFC2019/geo_cropped/]
make_baseline_1: false
augment: false

image_shape: [128, 128]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

baseline_epsilon: 1e-3
max_fov: 100.0

skip_bad_shape: true
near: -50.0
far: 75.0
baseline_scale_bounds: true
shuffle_val: true
test_len: -1
test_chunk_interval: 1
test_times_per_scene: 1